---
# WAN CE Nodes

type: spine

bgp_update_wait_install: false
bgp_as: 1000

spine: # dynamic_key: node_type
  defaults:
    loopback_ipv4_pool: 10.251.99.0/28
  nodes:
    - name: IntAgg1
      id: 1
      mgmt_ip: 192.168.0.56/24

custom_structured_configuration_router_bgp:
  router_id:

custom_structured_configuration_loopback_interfaces:
  - name: Loopback0
    ip_address: 

logging:
  format:
    timestamp: "traditional year timezone"
