
host_custom_structured_router_bgp:
  router_id: 10.0.0.3

host_custom_structured_loopback_interfaces:
- name: Loopback0
  ip_address: 10.0.0.3/32
  isis_passive: False
  node_segment:
    ipv4_index: 1
  eos_cli: |-
    node-segment ipv4 index 101 flex-algo LOWLATENCY
    node-segment ipv4 index 201 flex-algo CHEAPBW

host_custom_structured_router_isis:
  net: 49.0000.0000.0100.0003.00
  router_id: 10.0.0.3
  set_overload_bit:
    on_startup:
      delay: 300
  timers:
    local_convergence:
      protected_prefixes: True
    lsp:
      out_delay: 2000
  spf_interval:
    interval: 2
    wait_interval: 10
    hold_interval: 100
  advertise:
    passive_only: false

logging:
  format:
    timestamp: "traditional year timezone"

host_custom_structured_eos_cli: |-
  cfm
    profile POC
        continuity-check tx-interval 10 milliseconds
    !
    domain 5 level 5
        association 12
          direction up
          profile POC
          !
          end-point 1
  !
  tunnel-ribs
    tunnel-rib system-tunnel-rib
        source-protocol nexthop-group
        source-protocol rsvp-ler
        source-protocol bgp labeled-unicast
        source-protocol static
        source-protocol ldp
        source-protocol isis flex-algo preference 100
        source-protocol isis segment-routing
  !
  vlan 501
    name SVC4-L2EVPN
  !
  vlan 601
    name SVC6
  !
  vlan 1101
  !
  vrf instance SVC6
  !
  vrf instance SVC7
  !
  vrf instance SVC8
  !
  interface Ethernet1
    description PE1
    no switchport
    ip address 10.1.0.0/31
    bfd interval 50 min-rx 50 multiplier 3
    isis enable IGP
    isis network point-to-point
    traffic-engineering min-delay static 10 milliseconds
  !
  interface Ethernet2
    description PE4
    no switchport
    ip address 10.1.0.11/31
    bfd interval 50 min-rx 50 multiplier 3
    isis enable IGP
    isis network point-to-point
    traffic-engineering min-delay static 10 milliseconds
  !
  interface Ethernet5
    description CE1
    bgp session tracker ROUTE_REFLECTORS
    no switchport
    evpn ethernet-segment
        identifier 0020:2000:0000:0000:0000
        route-target import 20:20:00:00:00:00
    !
  !
  interface Ethernet5.101
    description SVC1-VPWS-SINGLE-2
    !
    encapsulation vlan
        client dot1q 101
  !
  interface Ethernet5.501
    description SVC4-L2EVPN
    vlan id 501
    !
    encapsulation vlan
      client dot1q 501
    !
    evpn ethernet-segment
        identifier 0020:0000:0000:0000:0501
        route-target import 00:20:00:00:05:01
    !
  !
  interface Ethernet5.601
    description SVC6-L3EVPN
    vlan id 601
    !
    encapsulation vlan
        client dot1q 601
  !
  interface Ethernet5.701
    description SVC7-4364
    encapsulation dot1q vlan 701
    vrf SVC7
    ip address 192.168.7.1/24
  !
  interface Ethernet5.801
    description SVC8-INTERWORKING
    encapsulation dot1q vlan 801
    vrf SVC8
    ip address 192.168.8.1/24
  !
  interface Ethernet5.1101
    description SVC10-GATEWAY
    vlan id 1101
    !
    encapsulation vlan
        client dot1q 1101
  !
  interface Loopback0
    ip address 10.0.0.3/32
    node-segment ipv4 index 3
    node-segment ipv4 index 101 flex-algo LOWLATENCY
    node-segment ipv4 index 201 flex-algo CHEAPBW
    isis enable IGP
  !
  interface Vlan601
    vrf SVC6
    ip address 192.168.6.1/24
  !
  ip virtual-router mac-address 00:1c:73:00:00:00
  !
  ip routing vrf SVC6
  ip routing vrf SVC7
  ip routing vrf SVC8
  !
  patch panel
    patch subintpo5.101
        connector 1 interface Ethernet5.101
        connector 2 pseudowire bgp vpws SVC1-VPWS-SINGLE-2 pseudowire pw1
    !
  router bgp 65000
    router-id 10.0.0.3
    maximum-paths 4 ecmp 4
    neighbor IBGP-PEER peer group
    neighbor IBGP-PEER remote-as 65000
    neighbor IBGP-PEER update-source Loopback0
    neighbor IBGP-PEER bfd
    neighbor IBGP-PEER session tracker ROUTE_REFLECTORS
    neighbor IBGP-PEER send-community
    neighbor IBGP-PEER maximum-routes 0
    neighbor 10.0.0.17 peer group IBGP-PEER
    neighbor 10.0.0.18 peer group IBGP-PEER
    !
    vlan 501
        rd 10.0.0.3:10501
        route-target both 0.0.0.0:10501
        redistribute learned
        redistribute static
    !
    vlan 1101
        rd 10.0.0.3:1101
        route-target both 0.0.0.0:1101
        redistribute learned
    !
    vpws SVC1-VPWS-SINGLE-2
        rd 10.0.0.3:11101
        route-target import export evpn 0.0.0.0:11101
        mpls control-word
        label flow
        !
        pseudowire pw1
          evpn vpws id local 11101 remote 21101
    !
    address-family evpn
        neighbor default encapsulation mpls next-hop-self source-interface Loopback0
        neighbor IBGP-PEER activate
    !
    address-family ipv4
        neighbor IBGP-PEER activate
        neighbor IBGP-PEER additional-paths receive
        neighbor IBGP-PEER additional-paths send limit 2
        redistribute connected
    !
    address-family vpn-ipv4
        neighbor IBGP-PEER activate
    !
    vrf SVC6
        rd 10.0.0.3:20601
        route-target import evpn 0.0.0.0:20601
        route-target export evpn 0.0.0.0:20601
        redistribute connected
        redistribute static
    !
    vrf SVC7
        rd 10.0.0.3:10701
        route-target import vpn-ipv4 0.0.0.0:10701
        route-target export vpn-ipv4 0.0.0.0:10701
        redistribute connected
        redistribute static
    !
    vrf SVC8
        rd 10.0.0.3:10801
        route-target import vpn-ipv4 0.0.0.0:20801
        route-target export vpn-ipv4 0.0.0.0:20801
        redistribute connected
        redistribute static
    !
    session tracker ROUTE_REFLECTORS
        recovery delay 600 seconds
  !
  router traffic-engineering
    flex-algo
        flex-algo 128 LOWLATENCY
          metric min-delay
          color 130
        !
        flex-algo 255 CHEAPBW
          color 230
  !
  router isis IGP
    net 49.0000.0000.0100.0003.00
    is-type level-2
    timers local-convergence-delay protected-prefixes
    set-overload-bit on-startup 300
    spf-interval 2 10 100
    timers lsp out-delay 2000
    !
    address-family ipv4 unicast
        fast-reroute ti-lfa mode node-protection
    !
    segment-routing mpls
        no shutdown
        segment path verification prefix-segment adjacency-segment
        flex-algo CHEAPBW level-2 advertised
        flex-algo LOWLATENCY level-2 advertised
  !
  end