
host_custom_structured_router_bgp:
  router_id: 10.0.0.4

host_custom_structured_loopback_interfaces:
- name: Loopback0
  ip_address: 10.0.0.4/32
  isis_passive: False
  node_segment:
    ipv4_index: 2
  eos_cli: |-
    node-segment ipv4 index 102 flex-algo LOWLATENCY
    node-segment ipv4 index 202 flex-algo CHEAPBW

host_custom_structured_router_isis:
  net: 49.0000.0000.0100.0004.00
  router_id: 10.0.0.4
  set_overload_bit:
    on_startup:
      delay: 300
  timers:
    local_convergence:
      protected_prefixes: True
    lsp:
      out_delay: 2000
  spf_interval:
    interval: 2
    wait_interval: 10
    hold_interval: 100
  advertise:
    passive_only: false

logging:
  format:
    sequence_numbers: True

host_custom_structured_eos_cli: |-
  tunnel-ribs
    tunnel-rib system-tunnel-rib
        source-protocol nexthop-group
        source-protocol rsvp-ler
        source-protocol bgp labeled-unicast
        source-protocol static
        source-protocol ldp
        source-protocol isis flex-algo preference 100
        source-protocol isis segment-routing preference 200
  !
  vlan 501
    name SVC4-L2EVPN
  !
  vlan 601
    name SVC6
  !
  vrf instance SVC6
  !
  vrf instance SVC7
  !
  vrf instance SVC8
  !
  interface Ethernet9.101
    description SVC1-VPWS-SINGLE-2
    !
    encapsulation vlan
        client dot1q 101
  !
  interface Ethernet9.501
    description SVC4-L2EVPN
    vlan id 501
    !
    encapsulation vlan
      client dot1q 501
    !
    evpn ethernet-segment
        identifier 0020:0000:0000:0000:0501
        route-target import 00:20:00:00:05:01
    !
  !
  interface Ethernet9.601
    description SVC6-L3EVPN
    vlan id 601
    !
    encapsulation vlan
        client dot1q 601
  !
  interface Ethernet9.701
    description SVC7-4364
    encapsulation dot1q vlan 701
    vrf SVC7
    ip address 192.168.107.1/24
  !
  interface Ethernet9.801
    description SVC8-INTERWORKING
    encapsulation dot1q vlan 801
    vrf SVC8
    ip address 192.168.108.1/24
  !
  interface Ethernet1
    description PE3
    no switchport
    ip address 10.1.0.10/31
    bfd interval 50 min-rx 50 multiplier 3
    isis enable IGP
    isis network point-to-point
    traffic-engineering min-delay static 10 milliseconds
  !
  interface Ethernet5
    description PE5
    no switchport
    ip address 10.1.0.9/31
    bfd interval 50 min-rx 50 multiplier 3
    isis enable IGP
    isis network point-to-point
    traffic-engineering min-delay static 10000 milliseconds
  !
  interface Ethernet9
    no switchport
    description CE1
    bgp session tracker ROUTE_REFLECTORS
    no switchport
    evpn ethernet-segment
        identifier 0020:2000:0000:0000:0000
        route-target import 20:20:00:00:00:00
    !
  !
  interface Loopback0
    ip address 10.0.0.4/32
    node-segment ipv4 index 4
    node-segment ipv4 index 102 flex-algo LOWLATENCY
    node-segment ipv4 index 202 flex-algo CHEAPBW
    isis instance IGP
  !
  interface Vlan601
    vrf SVC6
    ip address 192.168.206.1/24
  !
  ip routing vrf SVC6
  ip routing vrf SVC7
  ip routing vrf SVC8
  !
  patch panel
    patch subintpo9.101
        connector 1 interface Ethernet9.101
        connector 2 pseudowire bgp vpws SVC1-VPWS-SINGLE-2 pseudowire pw1
  !
  router bgp 65000
    router-id 10.0.0.4
    maximum-paths 4 ecmp 4
    neighbor IBGP-PEER peer group
    neighbor IBGP-PEER remote-as 65000
    neighbor IBGP-PEER update-source Loopback0
    neighbor IBGP-PEER bfd
    neighbor IBGP-PEER session tracker ROUTE_REFLECTORS
    neighbor IBGP-PEER send-community
    neighbor IBGP-PEER maximum-routes 0
    neighbor 10.0.0.17 peer group IBGP-PEER
    neighbor 10.0.0.18 peer group IBGP-PEER
    !
    vlan 501
        rd 10.0.0.4:10501
        route-target both 0.0.0.0:10501
        redistribute learned
        redistribute static
    !
    vlan 901
        rd 10.0.0.4:10901
        route-target both 0.0.0.0:10901
        redistribute learned
        redistribute static
    !
    vpws SVC1-VPWS-SINGLE-2
        rd 10.0.0.4:11101
        route-target import export evpn 0.0.0.0:11101
        mpls control-word
        label flow
        !
        pseudowire pw1
          evpn vpws id local 11101 remote 21101
    !
    address-family evpn
        neighbor default encapsulation mpls next-hop-self source-interface Loopback0
        next-hop mpls resolution ribs tunnel-rib colored system-colored-tunnel-rib tunnel-rib system-tunnel-rib
        neighbor IBGP-PEER activate
    !
    address-family ipv4
        neighbor IBGP-PEER activate
        neighbor IBGP-PEER additional-paths receive
        neighbor IBGP-PEER additional-paths send limit 2
        redistribute connected
    !
    address-family vpn-ipv4
        neighbor IBGP-PEER activate
    !
    vrf SVC6
        rd 10.0.0.4:20601
        route-target import evpn 0.0.0.0:20601
        route-target export evpn 0.0.0.0:20601
        redistribute connected
        redistribute static
    !
    vrf SVC7
        rd 10.0.0.4:10701
        route-target import vpn-ipv4 0.0.0.0:10701
        route-target export vpn-ipv4 0.0.0.0:10701
        redistribute connected
        redistribute static
    !
    vrf SVC8
        rd 10.0.0.4:10801
        route-target import evpn 0.0.0.0:20801
        route-target import vpn-ipv4 0.0.0.0:20801
        route-target export evpn 0.0.0.0:20801
        route-target export vpn-ipv4 0.0.0.0:20801
        redistribute connected
        redistribute static
    !
    session tracker ROUTE_REFLECTORS
        recovery delay 600 seconds
  !
  router traffic-engineering
    segment-routing
        rib system-colored-tunnel-rib
        !
        policy endpoint 10.0.0.3 color 30
          binding-sid 1000001
          name PE3_COLOR30
          !
          path-group preference 1
              segment-list label-stack 900001 900006 900005 900004 900003
    !
    flex-algo
        flex-algo 128 LOWLATENCY
          metric min-delay
          color 130
        !
        flex-algo 255 CHEAPBW
          color 230
  !
  router isis IGP
    net 49.0000.0000.0100.0004.00
    is-type level-2
    timers local-convergence-delay protected-prefixes
    set-overload-bit on-startup 300
    spf-interval 2 10 100
    timers lsp out-delay 2000
    !
    address-family ipv4 unicast
        fast-reroute ti-lfa mode node-protection
    !
    segment-routing mpls
        no shutdown
        flex-algo CHEAPBW level-2 advertised
        flex-algo LOWLATENCY level-2 advertised
  !